### DISCUSSION TITLE
Problem setting the blog on macOS

### DISCUSSION THREAD

**Discussion by loctran016** [uPagge/uBlogger#103] [Q&A] [answered]
Hello everyone and @uPagge , I've been trying to fix this problem but I can't find any solution. My repo is here: https://gitlab.com/cokaps/efi
![image](https://user-images.githubusercontent.com/64778285/120203899-6a369180-c252-11eb-9d2b-e64b5bc166d3.png)
I'm using the git module so I don't know how to fix the version in config
@

**Comment by Sp-cy** [comment]
just follow the instructions in the documentation and everything works.

**Reply by loctran016** [reply]
I did follow the guide, don't know why it doesn't work. Here is my config.toml:
```toml
baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en-us"
title = "My New Hugo Site"
# Change the default theme to be use when building the site with Hugo
theme = "uBlogger"
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
######################### THEME CONFIGURATIONS #################
[params]
  # uBlogger CHANGED | 0.2.0 uBlogger theme version
  version = "2.0.X"
  # site description
  description = "OpenCore and Clover EFI database for hackintosher"
  # site keywords
  keywords = ["Hackintosh","OpenCore","Clover","Apple","EFI"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://gitlab.com/cokaps/efi"
  # uBlogger NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
  # ("sha256", "sha384", "sha512", "md5")
  fingerprint = ""
  # uBlogger NEW | 0.2.0 date format
  dateFormat = "01-02-2021"
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]
  # uBlogger NEW | 0.2.0 App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "EFI Database"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"
  # uBlogger NEW | 0.2.0 Search config
  [params.search]
    enable = true
    # type of search engine ("lunr", "algolia")
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    # uBlogger NEW | 0.2.1 max number of results length
    maxResultLength = 10
    # uBlogger NEW | 0.2.3 snippet length of the result
    snippetLength = 30
    # uBlogger NEW | 0.2.1 HTML tag name of the highlight part in results
    highlightTag = "em"
    # uBlogger NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
  # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # uBlogger NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "EFI database"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
  # Footer config
  [params.footer]
    enable = true
    # uBlogger NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # uBlogger NEW | 0.2.0 whether to show Hugo and theme info
    hugo = true
    # uBlogger NEW | 0.2.0 whether to show copyright info
    copyright = true
    # uBlogger NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2021
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # uBlogger NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "02-01"
    # amount of RSS pages
    rss = 10
  # uBlogger NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10
  # Home page config
  [params.home]
    # uBlogger NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/avatar.png"
      # uBlogger CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "EFI database"
      # subtitle shown in home page
      subtitle = "Example for Hackintosher"
      # whether to show social links
      social = true
      # uBlogger NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = "Use this as your risk, I have no responsibility to you. You're recommended to follow Dortania guide before having a look at these EFIs"
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # uBlogger DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false
  # Social config about the author
  [params.social]
    GitHub = "xxxx"
    Linkedin = ""
    Twitter = "xxxx"
    Instagram = "xxxx"
    Facebook = "xxxx"
    Telegram = "xxxx"
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Email = "locphuc016@gmail.com"
    RSS = true # uBlogger NEW | 0.2.0
  # uBlogger CHANGED | 0.2.0 Page config
  [params.page]
    # uBlogger NEW | 1.0.0 main subject for articles, by default classic. more on themes}
    theme = "classic"
    # uBlogger NEW | 0.2.0 whether to hide a page from home page
    hiddenFromHomePage = false
    # uBlogger NEW | 0.2.0 whether to hide a page from search results
    hiddenFromSearch = false
    # uBlogger NEW | 1.2.0 Allows you to hide the preview image on the article page
    hiddenFeaturedImage = false
    # uBlogger NEW | 0.2.0 whether to enable twemoji
    twemoji = true
    # whether to enable lightgallery
    lightgallery = true
    # uBlogger NEW | 0.2.0 whether to enable the ruby extended syntax
    ruby = false
    # uBlogger NEW | 0.2.0 whether to enable the fraction extended syntax
    fraction = false
    # uBlogger NEW | 0.2.0 whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    # uBlogger NEW | 0.2.4 whether to show the full text content in RSS
    rssFullText = false
    # uBlogger NEW | 1.1.0 Post display settings on the page
    [params.summary]
      # uBlogger NEW | 1.1.0 Display previews on the page of posts
      hiddenImage = false
      # uBlogger NEW | 1.1.0 Allows you to hide the description
      hiddenDescription = false
      # uBlogger NEW | 1.1.0 Allows you to hide the title
      hiddenTitle = false
    # uBlogger NEW | 1.1.0 Tag display settings
    [params.summary.tags]
      # uBlogger NEW | 1.1.0 One of the options for displaying tags
      theme = "image"
      # uBlogger NEW | 1.1.0 Text color
      color = "white"
      # uBlogger NEW | 1.1.0 Backing color
      background = "black"
      # uBlogger NEW | 1.1.0 Tag transparency
      transparency = 0.9
    # uBlogger NEW | 1.2.0 Fasting time display
    [params.timeAgo]
      enable = "false"
      lang = "en"
    # uBlogger NEW | 0.2.0 Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # uBlogger NEW | 0.2.9 whether to keep the static table of the contents in front of the post
      keepStatic = true
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
    # uBlogger CHANGED | 0.2.0 KaTeX mathematical formulas
    [params.page.math]
      enable = false
      # default block delimiter is $$ ... $$ and \\[ ... \\]
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # default inline delimiter is $ ... $ and \\( ... \\)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = true
    # uBlogger NEW | 0.2.0 Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = false
      # the maximum number of lines of displayed code by default
      maxShownLines = 10
    # uBlogger NEW | 0.2.0 Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    # uBlogger CHANGED | 0.2.0 social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = true
      Renren = false
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false
    # uBlogger NEW | 0.2.7 Third-party library config
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/"
        # Or
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/"
        # Or
        # someJavascript = "https://cdn.example.com/some.js"
    # uBlogger CHANGED | 0.2.10 Page SEO config
    [params.page.seo]
      # image URL
      images = []
      # Publisher info
      [params.page.seo.publisher]
        name = "Cokaps"
        logoUrl = ""
    # uBlogger CHANGED | 1.1.0 Comment config
    [params.comment]
      enable = true
      # uBlogger NEW | 1.0.0
      # Remark42 comment config
      [params.comment.remark42]
        enable = false
        # the location of your server with Remark42
        host = "https://remark.example.com"
        # remark42 supports comments for several sites at once, this identifier indicates which site to display comments for.
        site = "you_site_key"
        # design theme
        theme = "light"
        # language
        locale = "en"
        # enable or disable smiley support
        emailSubscribe = "true"
      # Disqus comment config
      [params.comment.disqus]
        # uBlogger NEW | 0.1.1
        enable = false
        # Disqus shortname to use Disqus in posts
        shortname = ""
      # Gitalk comment config
      [params.comment.gitalk]
        # uBlogger NEW | 0.1.1
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine comment config
      [params.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        # uBlogger NEW | 0.2.6 emoji data file name, default is "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # located in "themes/uBlogger/assets/data/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/emoji/"
        emoji = ""
      # Facebook comment config
      [params.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      # uBlogger NEW | 0.2.0 Telegram comments config
      [params.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      # uBlogger NEW | 0.2.0 Commento comment config
      [params.comment.commento]
        enable = false
      # uBlogger NEW | 0.2.5 Utterances comment config
      [params.comment.utterances]
        enable = true
        # owner/repo
        repo="cokaps/comments"
        issue-term="url"
        label="Comments :tada: :tada: :tada:"
        lightTheme = "github-light"
        darkTheme = "github-dark"
  # Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
  # uBlogger NEW | 0.2.10 Site SEO config
  [params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""
  # uBlogger NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-SP1B5TQQBB"
      # whether to anonymize IP
      anonymizeIP = true
  # uBlogger NEW | 0.2.7 Cookie consent config
  [params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""
  # uBlogger CHANGED | 0.2.7 CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # located in "themes/uBlogger/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""
  # uBlogger NEW | 0.2.8 Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false
# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = false
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
# Author config
# uBlogger CHANGED | 1.0.0
[author]
  name = "Cokaps"
# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
# Permalinks config
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"
# Privacy config
[privacy]
  # uBlogger DELETED | 0.2.0 privacy of the Google Analytics (replaced by params.analytics.google)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]
# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false
# Options to make hugo output files
[outputs]
  # uBlogger CHANGED | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

```
