### DISCUSSION TITLE
[Question] Months names translations

### DISCUSSION THREAD

**Discussion by kszpieg** [uPagge/uBlogger#115] [Q&A] [answered]
Hello @uPagge 

Is there any way to translate the names of months? I mean, for example, if I am on the list of all posts in the English version of my site I have correct names. When I go to another language, let's say Polish, I still have in the same place the names of months but still in English. 

I assume that additional translation to the i18n file isn't enough (welp, I tried :D )and I have to change something in the code of the theme. Am I right?

Thanks in advance for the help.

**Comment by wblondel** [comment, marked as answer]
Hello,

This is how I got around this problem:

- I copied the `./themes/uBlogger/layouts/_default/section.html` file to `./layouts/_default/section.html`
- On line 28, I replaced 
```html
<div class="group-title-month">{{- .Key }}</div>
```
by
```html
<div class="group-title-month">{{- i18n .Key | default .Key }}</div>
```
It will first check for the translated name of the month, if not found it will show the default one (in English).

- In the i18n folder, I created a file for every language I want the months to be translated in, for example:

`./i18n/fr.yaml`
```yaml
# === Dates translation ===
# (hacky solution until Hugo supports dates i18n)

# Months
January:
  other: "Janvier"
February:
  other: "Février"
March:
  other: "Mars"
April:
  other: "Avril"
May:
  other: "Mai"
June:
  other: "Juin"
July:
  other: "Juillet"
August:
  other: "Août"
September:
  other: "Septembre"
October:
  other: "Octobre"
November:
  other: "Novembre"
December:
  other: "Décembre"
```
