### ISSUE TITLE
[BUG] New post doesn't show TOC

### ISSUE THREAD

**Issue by xiaochi-liu** [uPagge/uBlogger#36]
Hello. Thank you very much for this lovely theme. I like it. 

I'm using the `blogdown` R package and `.rmd` (R Markdown) document to build my website. 

However, I encountered a problem as follow:

### Describe the bug

My new post doesn't show TOC, although I've set the`toc` as `yes`.

### Expected behaviour

show TOC.

### Screenshots

Please see [this post](http://xiaochi.rbind.io/2021-02-13-writing-process/).

### Build Environment

- OS: macOS
- Theme version/commit: just download several days ago
- Hugo version: 0.80.0

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: macOS
- Browser: Chrome

### Additional Information

The YAML head of this post:

```
---
title: Writing Process
author: Xiaochi Liu
date: '2021-02-13'
slug: []
categories:
  - Scientific Writing
tags:
  - Scientific Writing
subtitle: ''
lastmod: '2021-02-13T22:28:04+11:00'
description: ''
summary: "Writing process for publication"
theme: classic
upd: ''
authorComment: ''
hiddenFromHomePage: no
hiddenFromSearch: no
resources:
  - name: featured-image
    src: featured-image.jpg

toc:
  enable: true
  auto: true
math:
  enable: yes
lightgallery: no
license: ''
---
```

And the full repo built by `blogdown` is [here](https://github.com/xiaochi-liu/My-Website).

Many thanks for your kind guidance
