### ISSUE TITLE
Different angles in articles previews

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [uPagge/uBlogger#37]
### Describe the bug
The corners of articles in the homepage have different angles only if the screen width is between 1200px and 960px.

### Expected behavior
Corners of the image inside the article preview should match its parent/cointainer.

### Screenshots

![image](https://user-images.githubusercontent.com/37159012/107865672-5a449e80-6e69-11eb-8759-a84f5a75b434.png)

### Preview Environment

- OS: Arch Linux
- Browser: Firefox (desktop and mobile)

### How to replicate the issue
Open the homepage of https://ublogger.netlify.app and resize the  window of your browser

**Comment by FedericoAntoniazzi** [comment]
I've just found out that the following code in _custom.scss fixes the issue.

```scss
$article-summary-image-border-radius: 19px;

.featured-image-preview, .featured-image {
  img {
    border-top-left-radius: $article-summary-image-border-radius;
    border-top-right-radius: $article-summary-image-border-radius;
  }
}
```

Shall I open a PR with this change?
