### ISSUE TITLE
[BUG] Avatar image placement seems incorrect

### ISSUE THREAD

**Issue by rwaal** [uPagge/uBlogger#44]
Thank you for creating and maintaining this awesome theme!

### Describe the bug

I have configured an avatar image in the `config.toml` file like this:

```toml
  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "richard.jpeg"
      title = "Welcome to my blog 👋"
      subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec faucibus tempus justo id feugiat. Praesent eget hendrerit massa. Vestibulum nec molestie lacus. Nunc eu tincidunt purus. Cras luctus laoreet mauris. Etiam metus sem, venenatis ac turpis sed, imperdiet porta enim."
      social = true

```
The problem is that my profile image is displayed above the text like this:

![image](https://user-images.githubusercontent.com/28002263/109114801-6caeba00-773e-11eb-995a-195fa762fadf.png)

I believe the image is supposed to be placed left of the text. Just like on the uBlogger page, like this:

![image](https://user-images.githubusercontent.com/28002263/109114365-cfec1c80-773d-11eb-9b81-0ab94538a442.png)

### Expected behavior

Avatar image is displayed on the left side of the text

### Build Environment

- OS: macOS Big Sur 11.2.1
- Theme commit: addce327bafbe7991baf2897def687b23a1864aa
- Hugo version: v0.80.0/extended

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: OS: macOS Big Sur 11.2.1
- Browser: Chrome, Safari
