### ISSUE TITLE
[BUG] images only render when post filename is named index

### ISSUE THREAD

**Issue by cmosetick** [uPagge/uBlogger#48]
### Describe the bug

Images related to a post page only render correctly when the file name prefix of a post is in the following format:

`index.en.md`

or some other 2 character language code

e.g.
`index.cn.md` etc.

No images render when a file name prefix is not named index.

Please note that within a post, I am unable to see rendered images when using *regular markdown* syntax such as the following in a test post:

`![sample image](foo-test.png "sample image test")`

### Expected behavior

Images should render regardless of what the file name prefix is.

for example:

`bar-foo-post.en.md`

### Front Matter code in post page

```
---
title: " Bar and Foo Image Test Post"

resources:
- name: "featured-image"
  src: "bar-sample-image.png"
- name: "foo-test"
  src: "foo-test.png"
---
```

### What actually happens

As soon as the final name is changed from `bar-foo-post.en.md` to `index.en.md` images start rendering as expected.

### Build Environment

- OS: macOS 10.15.7
- Theme version: 1.3.0
- Hugo version `hugo v0.81.0+extended darwin/amd64 BuildDate=unknown`
- `hugo server --disableFastRender`

### Preview Environment

- OS: macOS 10.15.7
- Browsers: Firefox, Brave
